apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  googleServiceAccount: config-connector@dojo-api-gateway-prod.iam.gserviceaccount.com
  mode: cluster
