{{- if .Values.pump.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    grafana-cloud.io/pod.monitor: "true"
  name: pump-monitor-{{ include "tyk-hybrid.fullname" . }}
  namespace: grafana-agent
spec:
  namespaceSelector:
    matchNames:
      - tyk
  podMetricsEndpoints:
    - port: tyk-metrics
      scheme: http
      honorLabels: true
      metricRelabelings:
        - action: drop
          regex: 'tyk_http_status_per_path'
          sourceLabels:
            - __name__
  selector:
    matchLabels:
      app: pump-{{ include "tyk-hybrid.fullname" . }}
{{- end }}